const jokes = [
  'Je moeder is zo dik dat ze in haar eentje al groepskorting krijgt',
  'Je moeder is zo lelijk dat ze niet eens kans maakt bij blinden',
  'Je moeder kan zo slecht schilderen, dat haar schilderijen zichzelf ophangen',
  'Het gewicht van jouw moeder is zo groot dat ze een integer overflow veroorzaakt',
  `Je moeder is zo dom, toen ik haar vertelde dat ze haar verstand verloor, ging ze er naar op zoek.`,
  `Je moeder is zo lelijk, toen ze naar een stripclub ging, betaalden ze haar om haar kleren aan te houden.`,
  `Je moeder is zo lelijk toen de kerstman door de schoorsteen kwam zei hij ho! ho! hoooollly shit!`,
  `Je moeder is zo lelijk dat ze een blind kind heeft laten huilen.`,
  `Je moeder is is zo stom toen dieven haar huis binnendrongen en de tv stal, ze achtervolgde hen schreeuwend: "wacht, je bent de afstandsbediening vergeten".`,
  `Ye moeder is als een toilet; dik, wit en ruikt naar stront.`,
  `Yo momma zo smerig dat wanneer ze naar de universele studio's gaat, kinderen haar volgen en roepen: "Shrek! Shrek!”`,
  `Je moeder is zo dom, dat ze dacht dat zeewier iets visrook was.`,
  `Je moeder is zo lelijk dat haar geboorteakte kwam met een excuusbrief van de condoomfabriek.`,
  `Je moeder is is zo stom toen een indringer haar huis binnendrong, rende ze naar beneden, draaide 9-1-1 op de magnetron en kon de knop "OPROEP" niet vinden.`,
  `Je moeder was zo oud dat mensen toen ze naar het museum gingen, dachten dat ze deel uitmaakte van een tentoonstelling.`,
  `Je moeder is zo dik als ze op de weegschaal stapt en zegt: 'een voor een, alsjeblieft.'`,
  `Je moeder is is zo dom dat ze over een lijn struikelde op een basketbalveld.`,
  `Je moeder is zo dik dat ze geen foto's maakt, ze neemt posters.`,
  `Je moeder is zo lelijk dat ze Chuck Norris bang maakt!`,
  `Je moeder is zo arm dat je familie cornflakes met een vork at om melk te besparen.`,
  `Je moeder is zo lelijk dat ze me eraan herinnert ZON, is moeilijk om naar haar te kijken.`,
  `Je moeder is zo vies dat ze de rechter en de linker bewaker moet gebruiken.`,
  `Je moeder is zo oud, dat als ze scheet laat komt er alleen maar stof uit.`,
  `Je moeder is zo dom, dat ze een lepel naar de Super Bowl nam.`,
  `Je moeder is zo arm dat ze haar auto heeft ingeruild voor gasgeld.`,
  `Je moeder is zo arm dat toen ik op een sigaret stapte ze zei: "wie heeft het vuur uitgezet?"`,
  `Je moeder is zo dom dat ze een bal op de grond gooide en miste.`,
  `Je moeder is zo harig, Kingkong werd jaloers.`,
  `Je moeder is zo zwart toen ik haar neerschoot, kwam de kogel terug en vroeg om een ​​zaklamp.`,
  `Je moeder zo arm dat ze toen ze een scheet liet, zei: "klap in je handen, stamp je voeten, prijs de heer, we hebben warmte!".`,
  `Je moeder is's adem is zo smerig, ik weet niet of ik haar Boterbroodjes of toiletpapier moet geven!`,
  `Je moeder is's adem is zo smerig dat als ze haar tanden boert, ik moet bukken.`,
  `Je moeder is zo dom dat ze de hele dag wachtte bij een stopbord.`,
  `Je moeder is is zo stom, toen ik haar crackers aanbood zei ze nee bedankt, ik ben vegetariër.`,
  `Je moeder is is zo dom, toen je werd geboren, keek ze naar je navelstreng en zei: "Er zit kabel bij!"`,
  `Je moeder is zo stom dat ze tegen de brievenbus schreeuwde. We vragen haar wat ze doet en ze zei dat ze een voicemail stuurde.`,
  `Je moeder is's zo dom dat ze een onderzoek niet heeft doorstaan.`,
  `Je moeder is zo oud, dat als ze scheet laat komt er alleen maar stof uit.`,
  `Je moeder is zo dik dat ze geen foto's maakt, ze neemt posters.`,
  `Je moeder is zo dik als ze op de weegschaal stapt en zegt: 'een voor een, alsjeblieft.'`,
  `Je moeder is zo arm dat de eenden brood naar haar gooien.`,
  `Je moeder zo lelijk dat ze een boemerang gooide en die weigerde terug te komen.`,
  `Je moeder is zo lelijk zelfs Bob de Bouwer zei: "We kunnen het niet repareren."`,
  `Je moeder is zo oud dat haar verjaardag is verlopen.`,
  `Je moeder is als een hockeyspeler, ze verandert haar pad niet gedurende drie periodes.`,
  `Je moeder is zo dom dat ze probeerde een afspraak te maken met Dr. Pepper`,
  `Je moeder zo lelijk dat wanneer ze in de spiegel glimlacht, de reflectie niet terug glimlacht.`,
  `Je moeder is zo stom toen ze een hond likte dat ze 'miauw' zei.`,
  `Je moeder is is zo plat, de laatste keer dat ze voelde dat een borst in een KFC-emmer zat.`,
  `​​Je moeder is is zo technologisch niet erg enthousiast dat ze stukjes kaas naast de computer weglaat!`,
  `Je moeder zo arm dat ik haar met één schoen in de vuilnisbak zag en ik zei: "Ben je een schoen verloren." En ze zei: "Nee, ik heb er net een gevonden."`,
  `Je moeder is zo lelijk als ze baden neemt, water springt eruit.`,
  `Je moeder is is zo dom dat ze een onderzoek mislukte.`,
  `Je moeder is zo dom dat ze 2 uur naar een sinaasappelsapcontainer staarde omdat er concentraat op stond.`,
  `Je moeder is zo dom, dat ze 2 kwartieren in haar oren legde en dacht dat ze naar 50 Cent luisterde.`,
  `Je moeder is zo dom dat ze zelfmoord probeerde te plegen door uit het kelderraam te springen.`,
  `Je moeder is zo dom dat ze een liniaal naar bed bracht om te zien hoe lang ze kon slapen.`,
  `Je moeder is zo dom dat ze denkt dat haar verrekijker een operaglazen is.`,
  `Je moeder is is zo dik, als ze een bontjas koopt, zal een hele soort uitsterven.`,
  `Je moeder is is zo dik dat ze transportwagens gebruikt als rolschaatsen.`,
  `Je moeder is net als mijn gsm-abonnement: altijd en overal 10 cent per minuut, geen beperkingen.`,
  `Je moeder is zo lelijk toen ze naar de bank liep, zetten ze de beveiligingscamera's uit.`,
  `Je moeder is zo dom dat ze een vis probeerde te verdrinken.`,
  `Je moeder is als de zon, staar haar aan en je wordt blind.`,
  `Je moeder is zo stom dat ze haar gezicht in een boek stak om een ​​Facebook te maken.`,
  `Je moeder is is zo lelijk dat haar vibrator zacht werd.`,
  `Je moeder is zo plat dat de muur jaloers op haar is.`,
  `Je moeder is is zo arm dat ze de vuilniswagen achterna zit met een boodschappenlijstje.`,
  `Je moeder is zo vies dat ze haar badwater niet eens voor waterboarden gebruiken.`,
  `Je moeder is zo lelijk, haar gezicht ziet eruit als de kont van een paard dat wappert in de wind.`,
  `Je moeder is zo dom dat ze een geventileerd condoom heeft uitgevonden.`,
  `Je moeder is zo getto, haar bruidstaart was gemaakt van maïsbrood.`,
  `Je moeder is zo dik, toen ze een baby was, nam ze een bad met een rubberen albatros.`,
  `Je papa is zo lelijk toen hij uit het raam keek dat hij werd gearresteerd voor mooning!`,
  `omma So Fat Grappen`,
  `Je moeder is zo dik dat ze meer kin heeft dan een telefoonboek in Hong Kong!`,
  `Je moeder is zo dik dat ze een houten been heeft met een standaard!`,
  `Je moeder is zo dik als ze op de weegschaal komt, zegt ze: "wordt vervolgd."`,
  `Je moeder zo dik dat ze Wheat Thicks eet.`,
  `Je moeder is zo dik dat we nu in haar zijn.`,
  `Je moeder zo dik dat ze haar been brak en jus uitgoot`,
  `Je moeder is zo dik als ze in een luchtballon rijdt, het lijkt erop dat ze een panty draagt!`,
  `Je moeder is zo dik dat ze het bad moeten invetten om haar eruit te krijgen!`,
  `Je moeder is zo dik dat ze een run in haar spijkerbroek heeft!`,
  `Je moeder is zo dik dat haar bloedgroep ragu is.`,
  `Je moeder is zo dik dat je het kozijn moet invetten en een twinkie aan de andere kant moet vasthouden om haar erdoorheen te krijgen`,
  `Je moeder is zo dik als ze naar een all you can buffet gaat, ze moeten verkeersdrempels installeren`,
  `Je moeder is zo dik dat ze haar eigen schoenen niet kan strikken`,
  `Je moeder is zo dik dat de auto alarm slaat wanneer ze rent`,
  `Je moeder is zo dik dat ze haar achterzak niet kan bereiken`,
  `Je moeder is zo dik dat ze een gele bus vol blanke kinderen zag en zei: "STOP DIE TWINKIE !! ”`,
  `Je moeder is zo dik, als ze rent laat ze de CD overslaan, bij het radiostation !!!`,
  `Je moeder is zo dik, toen ze naar buiten ging in een rode jurk, riep iedereen: "HEY, KOOL-AID!"`,
  `Je moeder is zo dik dat ze in de lucht sprong en vast kwam te zitten.`,
  `Je moeder is zo dik dat haar taille evenaar is!`,
  `Je moeder was zo dik dat ze naar Sea World moest gaan om zich te laten dopen.`,
  `Je moeder is zo dik dat ze haar broek op de oprit kon strijken.`,
  `Je moeder is zo dik dat ik haar mijn hele leven heb gekend ... en ik heb haar nog steeds niet allemaal gezien!`,
  `Je moeder is zo dik dat ze haar lippenstift opdeed met een verfroller`,
  `Je moeder is zo dik dat ze haar broek naar beneden moest trekken om in haar zakken te komen.`,
  `Je moeder is zo dik, haar benen zijn als verwende melk - wit en dik!`,
  `Je moeder is zo dik dat ik een trein en twee bussen moest nemen alleen maar om aan de goede kant te komen!`,
  `Je moeder was zo dik dat ze op een kwartier zat en een booger uit de neus van George Washington schoot`,
  `Je moeder is zo dik als ze springt, gaat ze recht naar de hel!`,
  `Je moeder is zo dik dat haar oudste foto's luchtfoto's moesten zijn!`,
  `Je moeder is zo dik als ze een Malcolm-X T-shirt draagt, proberen helikopters op haar rug te landen`,
  `Je moeder is zo dik dat ze redwoods gebruikt om haar tanden te plukken`,
  `Je moeder is zo dik dat de enige foto's die je van haar hebt satellietbeelden zijn`,
  `Je moeder is zo dik dat ze een paar BVD's aantrok en tegen de tijd dat ze haar middel bereikten, spelden ze boulevard uit`,
  `Je moeder is zo dik dat ze op een regenboog stapte en kegelen maakte`,
  `Je moeder is dus dikke mensen joggen om haar heen om te sporten.`,
  `Je moeder is zo dik, ze ging naar de film en ging naast iedereen zitten.`,
  `Je moeder is zo dik dat ze is uitgeroepen tot een natuurlijke habitat voor condors.`,
  `Je moeder is zo dik, je moet twee keer omrollen om van haar af te komen`,
  `Je moeder is zo dik dat ze in de oceaan dreef en Spanje claimde haar voor de nieuwe wereld.`,
  `Je moeder is als een autocoureur, ze verbrandt 50 rubbers per dag.`,
  `Je moeder is zo dik dat de laatste keer dat ze 90210 zag op de weegschaal stond!`,
  `Je moeder is zo lelijk, ze liep Taco Bell binnen en iedereen rende naar de grens.`,
  `Je moeder is is zo stom dat ze dacht dat een quarterback een terugbetaling is.`,
  `De bril van Je moeder is zo dik als ze naar een kaart kijkt dat ze mensen ziet zwaaien.`,
  `Je moeder is's haar is zo vettig als ze in de auto stapt, gaat het olielampje branden.`,
  `Je moeder is zo dik, ze binden een touw om haar schouders en slepen haar door een tunnel wanneer ze het willen schoonmaken.`,
  `Je moeder is zo arm dat ze op straat een blik schopte, vroeg wat ze aan het doen was en ze zei verhuizen.`,
  `Je moeder is de droom van een timmerman ... ze is plat als een plank en ze is nog nooit genaaid.`,
  `Je moeder is is zo dik dat ze meer kin heeft dan een Chinees telefoonboek.`,
];

/**
 * Get a random joke from the list
 */
const randomJoke = () => jokes[Math.floor(Math.random() * jokes.length)];

/**
 * Display a random joke in the console
 */
export const joke = (): void => {
  console.log(randomJoke());
};

/**
 * Get a random joke
 */
export const jokeString = (): string => {
  return randomJoke();
};
